### ISSUE TITLE
SET_ACTIVITY error

### ISSUE THREAD

**Issue by tilda** [diamondburned/osu-rpc-linux#1]
Hi!

I've tried out this script and there seems to be a error in it. ![](https://cursed-images.xyz/i/6vz.png)

I checked out stable 2.2 in my local git repo.

**Comment by diamondburned** [comment]
Looks like `details` is screwed up. Try installing the script first. If not, manually run `/opt/osu-rpc-linux/osu-conds`.

**Comment by tilda** [comment]
osu-conds returns nothing:
![](https://cursed-images.xyz/i/2ti.png)

**Comment by diamondburned** [comment]
Is this while osu! is idling or while playing a map?

**Comment by tilda** [comment]
I've only executed the script while idling/choosing a map but I'll try playing as well

**Comment by diamondburned** [comment]
Can you give me the output of `cat /etc/os-release`?

**Comment by tilda** [comment]
While playing a map it seems to work.
```
NAME="GalliumOS"
VERSION="2.1 (Xenon)"
ID=galliumos
ID_LIKE="ubuntu debian"
PRETTY_NAME="GalliumOS 2.1"
VERSION_ID="2.1"
HOME_URL="https://galliumos.org/"
SUPPORT_URL="https://galliumos.org/"
BUG_REPORT_URL="https://github.com/GalliumOS/galliumos-distro/issues"
VERSION_CODENAME=xenon
UBUNTU_CODENAME=xenial
```

**Comment by diamondburned** [comment]
In `stable-2.2`, the script executes `/etc/os-release` for the distro name. What I don't understand is that while in a map it works (which it doesn't print distro name), but not outside. Can you try `/etc/os-release && echo -n "${PRETTY_NAME}"`?

**Comment by tilda** [comment]
I might've found a problem: ![](https://cursed-images.xyz/i/77b.png)

**Comment by tilda** [comment]
Anyways I fixed that, and I get this:
![](https://cursed-images.xyz/i/hra.png)

**Comment by diamondburned** [comment]
For now, `sudo chmod +x /etc/os-release`. I'll write a workaround soon(tm).

**Comment by tilda** [comment]
Alright, thanks.

**Comment by tilda** [comment]
Actually, the issue still happens for some reason.

**Comment by tilda** [comment]
Will try.
